[package]
name = "sensor-data-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.2"
link-lib = { path = "../link-lib" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
chrono = "0.4.30"
egui = "0.22.0"
eframe = "0.22.0"
env_logger = "0.10.0"
